# Generated by Django 2.1.8 on 2019-04-05 08:15

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('code', models.CharField(db_column='Code', max_length=1, primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=50, null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=50, null=True)),
                ('sort_order', models.IntegerField(blank=True, db_column='SortOrder', null=True)),
            ],
            options={
                'db_table': 'tblGender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insuree',
            fields=[
                ('id', models.AutoField(db_column='InsureeID', primary_key=True, serialize=False)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('chf_id', models.CharField(blank=True, db_column='CHFID', max_length=12, null=True)),
                ('last_name', models.CharField(db_column='LastName', max_length=100)),
                ('other_names', models.CharField(db_column='OtherNames', max_length=100)),
                ('dob', core.fields.DateField(db_column='DOB')),
                ('head', models.BooleanField(db_column='IsHead')),
                ('marital', models.CharField(blank=True, db_column='Marital', max_length=1, null=True)),
                ('passport', models.CharField(blank=True, max_length=25, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('current_address', models.CharField(blank=True, db_column='CurrentAddress', max_length=200, null=True)),
                ('geolocation', models.CharField(blank=True, db_column='GeoLocation', max_length=250, null=True)),
                ('current_village', models.IntegerField(blank=True, db_column='CurrentVillage', null=True)),
                ('photo_date', core.fields.DateField(blank=True, db_column='PhotoDate', null=True)),
                ('card_issued', models.BooleanField(db_column='CardIssued')),
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom')),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('offline', models.BooleanField(blank=True, db_column='isOffline', null=True)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
                ('row_id', models.BinaryField(blank=True, db_column='RowID', null=True)),
            ],
            options={
                'db_table': 'tblInsuree',
                'managed': False,
            },
        ),
    ]
