# Generated by Django 2.1.11 on 2019-10-02 19:40

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0002_family_familytype_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsureePolicy',
            fields=[
                ('id', models.AutoField(db_column='InsureePolicyID', primary_key=True, serialize=False)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('enrollment_date', core.fields.DateField(blank=True, db_column='EnrollmentDate', null=True)),
                ('start_date', core.fields.DateField(blank=True, db_column='StartDate', null=True)),
                ('effective_date', core.fields.DateField(blank=True, db_column='EffectiveDate', null=True)),
                ('expiry_date', core.fields.DateField(blank=True, db_column='ExpiryDate', null=True)),
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom')),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('offline', models.BooleanField(blank=True, db_column='isOffline', null=True)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
            ],
            options={
                'db_table': 'tblInsureePolicy',
                'managed': False,
            },
        ),
    ]
