# Generated by Django 3.0.3 on 2020-07-22 08:39

from django.db import migrations


def cleanup_current_village(apps, schema_editor):
    Insuree = apps.get_model('insuree', 'Insuree')
    Insuree.objects.filter(current_village=0).update(current_village=None)


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0005_identificationtype'),
    ]

    operations = [
        migrations.RunPython(cleanup_current_village),
    ]
