# Generated by Django 3.0.3 on 2020-08-07 13:09
from django.conf import settings

import core.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0010_auto_20200731_0524'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE "tblPhotos" ADD "LegacyID" int NULL, photo TEXT null'
            if settings.MSSQL else
            'ALTER TABLE "tblPhotos" ADD "LegacyID" int; ALTER TABLE "tblPhotos" add photo TEXT;'
        ),
        migrations.RunSQL(
            'ALTER TABLE "tblPhotos" ALTER COLUMN "PhotoFolder" nvarchar(255) NULL'
            if settings.MSSQL else
            'ALTER TABLE "tblPhotos" ALTER COLUMN "PhotoFolder" TYPE VARCHAR(255); '
            'ALTER TABLE "tblPhotos" ALTER COLUMN "PhotoFolder" DROP NOT NULL;'
        ),
        migrations.RunSQL(
            'ALTER TABLE "tblPhotos" ALTER COLUMN "PhotoFileName" nvarchar(255) NULL'
            if settings.MSSQL else
            'ALTER TABLE "tblPhotos" ALTER COLUMN "PhotoFileName" TYPE VARCHAR(255);'
            'ALTER TABLE "tblPhotos" ALTER COLUMN "PhotoFileName" DROP NOT NULL;'
        ),
        migrations.CreateModel(
            name='InsureePhoto',
            fields=[
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='PhotoID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='PhotoUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('insuree_id', models.IntegerField(blank=True, db_column='InsureeID', null=True)),
                ('chf_id', models.CharField(blank=True, db_column='CHFID', max_length=12, null=True)),
                ('folder', models.CharField(db_column='PhotoFolder', max_length=255)),
                ('filename', models.CharField(blank=True, db_column='PhotoFileName', max_length=250, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('officer_id', models.IntegerField(db_column='OfficerID')),
                ('date', core.fields.DateField(db_column='PhotoDate')),
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom')),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('audit_user_id', models.IntegerField(blank=True, db_column='AuditUserID', null=True)),
            ],
            options={
                'db_table': 'tblPhotos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
