# Generated by Django 3.2.17 on 2023-06-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0013_auto_20211103_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insuree',
            options={'managed': True},
        ),
    ]
