# Generated by Django 3.2.17 on 2023-03-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0013_auto_20211103_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsureeAttachment',
            fields=[
                ('idAttachment', models.AutoField(primary_key=True, serialize=False)),
                ('folder', models.CharField(db_column='Folder', max_length=250)),
                ('name', models.CharField(db_column='FileName', max_length=250)),
                ('insuree', models.ManyToManyField(to='insuree.Insuree')),
            ],
            options={
                'db_table': 'tblattachment',
            },
        ),
    ]
