# Generated by Django 3.2.17 on 2023-03-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0014_insureeattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipGroup',
            fields=[
                ('idMembershipgroup', models.AutoField(db_column='idMembershipGroup', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=250, null=True)),
            ],
            options={
                'db_table': 'tblMembershipGroup',
            },
        ),
        migrations.AlterModelOptions(
            name='insuree',
            options={'managed': True},
        ),
    ]
