# Generated by Django 3.2.17 on 2023-06-19 11:58

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0014_alter_insuree_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuree',
            name='dead',
            field=models.BooleanField(db_column='Dead', default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuree',
            name='deathReason',
            field=models.CharField(db_column='DeathReason', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='insuree',
            name='dod',
            field=core.fields.DateField(db_column='DOD', null=True),
        ),
    ]
