# Generated by Django 3.2.18 on 2023-05-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0014_add_missing_fields_to_django_scheme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmationtype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='familytype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='identificationtype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='insuree',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='insureephoto',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='insureepolicy',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='policyrenewaldetail',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='relation',
            options={'managed': True},
        ),
    ]
