# Generated by Django 3.2.17 on 2023-03-30 12:10

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0015_auto_20230330_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuree',
            name='row_id',
        ),
        migrations.AddField(
            model_name='insuree',
            name='membershipgroup',
            field=models.ForeignKey(blank=True, db_column='MembershipGroupID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurees', to='insuree.membershipgroup'),
        ),
    ]
