# Generated by Django 3.2.19 on 2023-06-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0015_auto_20230619_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuree',
            name='dead',
            field=models.BooleanField(blank=True, db_column='Dead', default=False, null=True),
        ),
    ]
