# Generated by Django 3.2.21 on 2023-09-19 15:35

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0016_alter_jsonext_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuree',
            name='chf_id',
            field=models.CharField(blank=True, db_column='CHFID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insuree',
            name='dob',
            field=core.fields.DateField(blank=True, db_column='DOB', null=True),
        ),
        migrations.AlterField(
            model_name='insuree',
            name='head',
            field=models.BooleanField(db_column='IsHead', default=False),
        ),
    ]
