# Generated by Django 3.2.23 on 2024-02-02 16:06

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0016_auto_20230623_0515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'managed': True},
        ),
        migrations.AddIndex(
            model_name='insuree',
            index=models.Index(fields=['legacy_id', 'validity_from', 'validity_to', 'chf_id'], name='tblInsuree_LegacyI_a4548b_idx'),
        ),
    ]
