# Generated by Django 3.2.17 on 2023-05-17 09:44

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0016_auto_20230330_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuree',
            name='chf_id',
            field=models.CharField(blank=True, db_column='CHFID', max_length=13, null=True),
        ),
    ]
