# Generated by Django 3.2.21 on 2023-09-12 15:31

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0016_alter_jsonext_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuree',
            name='dead',
            field=models.BooleanField(blank=True, db_column='Dead', default=False, null=True),
        ),
        migrations.AddField(
            model_name='insuree',
            name='deathReason',
            field=models.CharField(db_column='DeathReason', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='insuree',
            name='dod',
            field=core.fields.DateField(db_column='DOD', null=True),
        ),
    ]
