# Generated by Django 3.2.17 on 2023-06-09 10:14

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0017_auto_20230517_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insureephoto',
            options={'managed': True},
        ),
    ]
