# Generated by Django 3.2.23 on 2024-02-02 16:07

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0017_auto_20240202_1606'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['legacy_id', 'validity_from', 'validity_to'], name='tblFamilies_LegacyI_5129e4_idx'),
        ),
    ]
