# Generated by Django 3.2.16 on 2023-10-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0017_auto_20230923_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationtype',
            name='is_confirmation_number_required',
            field=models.BooleanField(default=False),
        ),
    ]
