# Generated by Django 3.2.20 on 2023-07-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0015_set_managed_to_true_in_all_models'),
        ('insuree', '0019_auto_20230609_1016'),
    ]

    operations = [
    ]
