# Generated by Django 4.2.11 on 2024-06-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0019_auto_20231026_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='uuid',
        ),
    ]
