# Generated by Django 4.2.11 on 2024-05-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0019_auto_20231026_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuree',
            name='card_issued',
            field=models.BooleanField(blank=True, db_column='CardIssued', null=True),
        ),
    ]
