# Generated by Django 3.2.23 on 2024-03-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0020_auto_20240321_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuree',
            name='row_id',
        ),
        migrations.AddField(
            model_name='family',
            name='coordinates',
            field=models.CharField(blank=True, db_column='Coordinates', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='poligamous',
            field=models.BooleanField(blank=True, db_column='PoligamousFamily', null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='preferred_payment_method',
            field=models.CharField(blank=True, db_column='PreferredPaymentMethod', max_length=50, null=True),
        ),
    ]
