# Generated by Django 4.2.11 on 2024-06-04 09:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0020_remove_family_uuid'),
    ]

    def update_uuids(app, schema_editor):
        Family = app.get_model('insuree', 'Family')

        # Generate uuid from Family
        for family in Family.objects.all():
            family.uuid = uuid.uuid4()
            family.save()

    operations = [
        migrations.AddField(
            model_name='family',
            name='uuid',
            field=models.UUIDField(blank=True, db_column='FamilyUUID', null=True, unique=True),
        ),
        migrations.RunPython(update_uuids)
    ]
