# Generated by Django 4.2.11 on 2024-06-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0021_family_uuid'),
    ]

    def update_uuid(app, schema_editor):
        Family = app.get_model('insuree', 'Family')
        Insuree = app.get_model('insuree', 'Insuree')
        FamilyMutation = app.get_model('insuree', 'familymutation')

        # Update family_uuid in insuree
        for insuree in Insuree.objects.all():
            if insuree.family_id:
                family = Family.objects.get(id=insuree.family_id)
                insuree.family_uuid = family.uuid
                insuree.save()

        # Update family_uuid in family_munation
        for mutation in FamilyMutation.objects.all():
            family = Family.objects.filter(id=mutation.family_id).first()
            if family:
                mutation.family_uuid = family.uuid
                mutation.save()

    operations = [
        migrations.AddField(
            model_name='familymutation',
            name='family_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuree',
            name='family_uuid',
            field=models.UUIDField(blank=True, db_column='FamilyUUID', null=True),
        ),
        migrations.RunPython(update_uuid)
    ]
