# Generated by Django 3.2.23 on 2024-03-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0021_auto_20240321_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='bank_coordinates',
            field=models.CharField(blank=True, db_column='BankCoordinates', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='professional_situation',
            field=models.CharField(blank=True, db_column='ProfessionalSituation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insuree',
            name='bank_coordinates',
            field=models.CharField(blank=True, db_column='BankCoordinates', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insuree',
            name='coordinates',
            field=models.CharField(blank=True, db_column='Coordinates', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insuree',
            name='poligamous',
            field=models.BooleanField(blank=True, db_column='PoligamousFamily', null=True),
        ),
        migrations.AddField(
            model_name='insuree',
            name='preferred_payment_method',
            field=models.CharField(blank=True, db_column='PreferredPaymentMethod', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='insuree',
            name='professional_situation',
            field=models.CharField(blank=True, db_column='ProfessionalSituation', max_length=255, null=True),
        ),
    ]
