# Generated by Django 4.2.14 on 2024-08-29 14:46

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0021_alter_insureephoto_chf_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insureephoto',
            name='date',
            field=core.fields.DateField(blank=True, db_column='PhotoDate', null=True),
        ),
        migrations.AlterField(
            model_name='insureephoto',
            name='officer_id',
            field=models.IntegerField(blank=True, db_column='OfficerID', null=True),
        ),
    ]
