# Generated by Django 3.2.23 on 2024-03-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0021_auto_20240321_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeLevels',
            fields=[
                ('id', models.AutoField(db_column='IncomeLevelID', primary_key=True, serialize=False)),
                ('french_version', models.CharField(blank=True, db_column='FrenchVersion', max_length=200, null=True)),
                ('english_version', models.CharField(blank=True, db_column='EnglishVersion', max_length=200, null=True)),
            ],
            options={
                'db_table': 'tblIncomeLevels',
                'managed': True,
            },
        ),
    ]
