# Generated by Django 3.2.23 on 2024-03-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0022_auto_20240321_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='income_level',
            field=models.ForeignKey(blank=True, db_column='IncomeLevel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.incomelevels'),
        ),
        migrations.AddField(
            model_name='insuree',
            name='income_level',
            field=models.ForeignKey(blank=True, db_column='IncomeLevel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.incomelevels'),
        ),
    ]
