# Generated by Django 4.2.11 on 2024-06-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0022_familymutation_family_uuid_insuree_family_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymutation',
            name='family',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='insuree',
            name='family',
            field=models.IntegerField(blank=True, db_column='FamilyID', null=True),
        ),
    ]
