# Generated by Django 4.2.23 on 2025-12-02 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0023_alter_family_head_insuree'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='parent_family',
            field=models.ForeignKey(blank=True, db_column='ParentFamily', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_families', to='insuree.family'),
        ),
        migrations.AddField(
            model_name='family',
            name='polygamous_family',
            field=models.BooleanField(blank=True, db_column='PoligamousFamily', default=False, null=True),
        ),
    ]
