# Generated by Django 4.2.11 on 2024-06-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0023_alter_familymutation_family_alter_insuree_family'),
    ]

    def update_uuid(app, schema_editor):
        Family = app.get_model('insuree', 'family')

        for family in Family.objects.filter(legacy_id__isnull=False):
            f = Family.objects.filter(id=family.legacy_id).first()
            if f:
                family.legacy_uuid = f.uuid
                family.save()

    operations = [
        migrations.AddField(
            model_name='family',
            name='legacy_uuid',
            field=models.UUIDField(blank=True, db_column='LegacyUUID', null=True),
        ),
        migrations.RunPython(update_uuid)
    ]
