# Generated by Django 4.2.11 on 2024-06-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0024_family_legacy_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='id',
        ),
        migrations.AlterField(
            model_name='family',
            name='uuid',
            field=models.UUIDField(db_column='FamilyUUID', primary_key=True, serialize=False, unique=True),
        ),
    ]
