# Generated by Django 4.2.11 on 2024-06-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0025_remove_family_id_alter_family_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='uuid',
            new_name='id',
        ),
    ]
