# Generated by Django 4.2.16 on 2024-10-18 12:47

from django.db import migrations
from django.db import models

class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0026_rename_family_poligamous_remove_insuree_poligamous_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomelevels',
            old_name='french_version',
            new_name='first_language',
        ),
        migrations.RenameField(
            model_name='incomelevels',
            old_name='english_version',
            new_name='second_language',
        ),
        migrations.AlterField(
            model_name='incomelevels',
            name='first_language',
            field=models.CharField(db_column='FirstLanguage', max_length=200, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incomelevels',
            name='second_language',
            field=models.CharField(db_column='SecondLanguage', max_length=200, blank=True, null=True),
        ),
    ]
