# Generated by Django 4.2.11 on 2024-06-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0026_rename_uuid_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(db_column='FamilyID', primary_key=True, serialize=False, unique=True),
        ),
    ]
