# Generated by Django 4.2.16 on 2025-04-23 12:01

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0027_rename_fields_incomelevels_english_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyAttachment',
            fields=[
                ('idAttachment', models.AutoField(db_column='idAttachment', primary_key=True, serialize=False)),
                ('folder', models.CharField(db_column='Folder', max_length=250, null=True)),
                ('filename', models.CharField(db_column='FileName', max_length=250, null=True)),
                ('title', models.CharField(db_column='Title', max_length=250, null=True)),
                ('date', core.fields.DateField(blank=True, db_column='AttachmentDate', null=True)),
                ('document', models.TextField()),
                ('mime', models.CharField(db_column='Mime', max_length=250)),
                ('family', models.ForeignKey(db_column='FamilyID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachments', to='insuree.family')),
            ],
            options={
                'db_table': 'tblAttachment',
            },
        ),
    ]
