# Generated by Django 4.2.11 on 2024-06-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0028_remove_insuree_family_uuid_alter_insuree_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymutation',
            name='family',
        ),
    ]
