# Generated by Django 4.2.16 on 2025-05-20 12:01
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0028_familyattachment'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE [tblRelations] SET [Relation]='Head of family', [AltLanguage]='Chef de ménage' WHERE [RelationId]=1;"
            if settings.MSSQL else
            """UPDATE "tblRelations" SET "Relation"='Head of family', "AltLanguage"='Chef de ménage' WHERE "RelationId"=1;"""
        ),
        migrations.RunSQL(
            "UPDATE [tblRelations] SET [Relation]='Spouse', [AltLanguage]='Époux/Epouse' WHERE [RelationId]=2;"
            if settings.MSSQL else
            """UPDATE "tblRelations" SET "Relation"='Spouse', "AltLanguage"='Époux/Epouse' WHERE "RelationId"=2;"""
        ),
        migrations.RunSQL(
            "UPDATE [tblRelations] SET [Relation]='Son/Daughter', [AltLanguage]='Fils/Fille' WHERE [RelationId]=3;"
            if settings.MSSQL else
            """UPDATE "tblRelations" SET "Relation"='Son/Daughter', "AltLanguage"='Fils/Fille' WHERE "RelationId"=3;"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblRelations] ([RelationId], [Relation], [AltLanguage]) VALUES (21, 'Mother of head', 'Mère chef');"
            if settings.MSSQL else
            """INSERT INTO "tblRelations" ("RelationId", "Relation", "AltLanguage") VALUES (21, 'Mother of head', 'Mère chef');"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblRelations] ([RelationId], [Relation], [AltLanguage]) VALUES (22, 'Mother of spouse', 'Mère conjointe');"
            if settings.MSSQL else
            """INSERT INTO "tblRelations" ("RelationId", "Relation", "AltLanguage") VALUES (22, 'Mother of spouse', 'Mère conjointe');"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblRelations] ([RelationId], [Relation], [AltLanguage]) VALUES (23, 'Father of head', 'Père chef');"
            if settings.MSSQL else
            """INSERT INTO "tblRelations" ("RelationId", "Relation", "AltLanguage") VALUES (23, 'Father of head', 'Père chef');"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblRelations] ([RelationId], [Relation], [AltLanguage]) VALUES (24, 'Father of spouse', 'Père conjointe');"
            if settings.MSSQL else
            """INSERT INTO "tblRelations" ("RelationId", "Relation", "AltLanguage") VALUES (24, 'Father of spouse', 'Père conjointe');"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblRelations] ([RelationId], [Relation], [AltLanguage]) VALUES (25, 'Other members', 'Autres membres');"
            if settings.MSSQL else
            """INSERT INTO "tblRelations" ("RelationId", "Relation", "AltLanguage") VALUES (25, 'Other members', 'Autres membres');"""
        ),
        migrations.RunSQL(
            "UPDATE [tblInsuree] SET [Relationship]=25 WHERE [Relationship] IN (4, 5, 6, 7, 8);"
            if settings.MSSQL else
            """UPDATE "tblInsuree" SET "Relationship"=25 WHERE "Relationship" IN (4, 5, 6, 7, 8);"""
        ),
        migrations.RunSQL(
            "DELETE FROM [tblRelations] WHERE [RelationId] IN (4, 5, 6, 7, 8);"
            if settings.MSSQL else
            """DELETE FROM "tblRelations" WHERE "RelationId" IN (4, 5, 6, 7, 8);"""
        ),
    ]
