# Generated by Django 4.2.16 on 2025-05-20 12:01
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0029_altertblRelations'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE [tblEducations] SET [Education]='Normal school curriculum', [AltLanguage]='Cursus scolaire normal' WHERE [EducationId]=1;"
            if settings.MSSQL else
            """UPDATE "tblEducations" SET "Education"='Normal school curriculum', "AltLanguage"='Cursus scolaire normal' WHERE "EducationId"=1;"""
        ),
        migrations.RunSQL(
            "UPDATE [tblEducations] SET [Education]='Vocational training/apprenticeship', [AltLanguage]='Formation professionnelle/apprentissage' WHERE [EducationId]=2;"
            if settings.MSSQL else
            """UPDATE "tblEducations" SET "Education"='Vocational training/apprenticeship', "AltLanguage"='Formation professionnelle/apprentissage' WHERE "EducationId"=2;"""
        ),
        migrations.RunSQL(
            "UPDATE [tblInsuree] SET [Education]=2 WHERE [Education] NOT IN (1, 2);"
            if settings.MSSQL else
            """UPDATE "tblInsuree" SET "Education"=2 WHERE "Education" NOT IN (1, 2);"""
        ),
        migrations.RunSQL(
            "DELETE FROM [tblEducations] WHERE [EducationId] NOT IN (1, 2);"
            if settings.MSSQL else
            """DELETE FROM "tblEducations" WHERE "EducationId" NOT IN (1, 2);"""
        ),
    ]
