# Generated by Django 4.2.16 on 2025-05-20 12:01
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0030_altertblEducation'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE [tblProfessions] SET [Profession]='Without profession', [AltLanguage]='Sans profession' WHERE [ProfessionId]=1;"
            if settings.MSSQL else
            """UPDATE "tblProfessions" SET "Profession"='Without profession', "AltLanguage"='Sans profession' WHERE "ProfessionId"=1;"""
        ),
        migrations.RunSQL(
            "UPDATE [tblProfessions] SET [Profession]='Farmer/Fisherman/Breeder/or Artisan', [AltLanguage]='Agriculteur exploitant/Pêcheur/Éleveur/ou Artisan' WHERE [ProfessionId]=2;"
            if settings.MSSQL else
            """UPDATE "tblProfessions" SET "Profession"='Farmer/Fisherman/Breeder/or Artisan', "AltLanguage"='Agriculteur exploitant/Pêcheur/Éleveur/ou Artisan' WHERE "ProfessionId"=2;"""
        ),
        migrations.RunSQL(
            "UPDATE [tblProfessions] SET [Profession]='Traders and similar', [AltLanguage]='Commerçants et assimilés' WHERE [ProfessionId]=3;"
            if settings.MSSQL else
            """UPDATE "tblProfessions" SET "Profession"='Traders and similar', "AltLanguage"='Commerçants et assimilés' WHERE "ProfessionId"=3;"""
        ),
        migrations.RunSQL(
            "UPDATE [tblProfessions] SET [Profession]='Company director', [AltLanguage]='Chef d''entreprise' WHERE [ProfessionId]=4;"
            if settings.MSSQL else
            """UPDATE "tblProfessions" SET "Profession"='Company director', "AltLanguage"='Chef d''entreprise' WHERE "ProfessionId"=4;"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblProfessions] ([ProfessionId], [Profession], [AltLanguage]) VALUES (5, 'Self-employed', 'Professionnel libéral');"
            if settings.MSSQL else
            """INSERT INTO "tblProfessions" ("ProfessionId", "Profession", "AltLanguage") VALUES (5, 'Self-employed', 'Professionnel libéral');"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblProfessions] ([ProfessionId], [Profession], [AltLanguage]) VALUES (6, 'Teacher', 'Enseignant');"
            if settings.MSSQL else
            """INSERT INTO "tblProfessions" ("ProfessionId", "Profession", "AltLanguage") VALUES (6, 'Teacher', 'Enseignant');"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblProfessions] ([ProfessionId], [Profession], [AltLanguage]) VALUES (7, 'Researcher-teacher', 'Enseignant chercheur');"
            if settings.MSSQL else
            """INSERT INTO "tblProfessions" ("ProfessionId", "Profession", "AltLanguage") VALUES (7, 'Researcher-teacher', 'Enseignant chercheur');"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblProfessions] ([ProfessionId], [Profession], [AltLanguage]) VALUES (8, 'Doctor', 'Médecin');"
            if settings.MSSQL else
            """INSERT INTO "tblProfessions" ("ProfessionId", "Profession", "AltLanguage") VALUES (8, 'Doctor', 'Médecin');"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblProfessions] ([ProfessionId], [Profession], [AltLanguage]) VALUES (9, 'Other healthcare professional', 'Autre professionnel de Santé');"
            if settings.MSSQL else
            """INSERT INTO "tblProfessions" ("ProfessionId", "Profession", "AltLanguage") VALUES (9, 'Other healthcare professional', 'Autre professionnel de Santé');"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblProfessions] ([ProfessionId], [Profession], [AltLanguage]) VALUES (10, 'Authority of the public administration', 'Autorité de l''admin. publique');"
            if settings.MSSQL else
            """INSERT INTO "tblProfessions" ("ProfessionId", "Profession", "AltLanguage") VALUES (10, 'Authority of the public administration', 'Autorité de l''admin. publique');"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblProfessions] ([ProfessionId], [Profession], [AltLanguage]) VALUES (11, 'Public administration employee', 'Employé de l''administration publique');"
            if settings.MSSQL else
            """INSERT INTO "tblProfessions" ("ProfessionId", "Profession", "AltLanguage") VALUES (11, 'Public administration employee', 'Employé de l''administration publique');"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblProfessions] ([ProfessionId], [Profession], [AltLanguage]) VALUES (12, 'Administrative or commercial employee of a company', 'Employé administratif ou commercial d''entreprise');"
            if settings.MSSQL else
            """INSERT INTO "tblProfessions" ("ProfessionId", "Profession", "AltLanguage") VALUES (12, 'Administrative or commercial employee of a company', 'Employé administratif ou commercial d''entreprise');"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblProfessions] ([ProfessionId], [Profession], [AltLanguage]) VALUES (13, 'Company Engineer and Technician', 'Ingénieur et Technicien d''entreprise');"
            if settings.MSSQL else
            """INSERT INTO "tblProfessions" ("ProfessionId", "Profession", "AltLanguage") VALUES (13, 'Company Engineer and Technician', 'Ingénieur et Technicien d''entreprise');"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblProfessions] ([ProfessionId], [Profession], [AltLanguage]) VALUES (14, 'Self-employed engineer and technician', 'Ing. et Technicien travaillant à son compte');"
            if settings.MSSQL else
            """INSERT INTO "tblProfessions" ("ProfessionId", "Profession", "AltLanguage") VALUES (14, 'Self-employed engineer and technician', 'Ing. et Technicien travaillant à son compte');"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblProfessions] ([ProfessionId], [Profession], [AltLanguage]) VALUES (15, 'Clergy, religious', 'Clergé, religieux');"
            if settings.MSSQL else
            """INSERT INTO "tblProfessions" ("ProfessionId", "Profession", "AltLanguage") VALUES (15, 'Clergy, religious', 'Clergé, religieux');"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblProfessions] ([ProfessionId], [Profession], [AltLanguage]) VALUES (16, 'Police and military', 'Policier et militaire');"
            if settings.MSSQL else
            """INSERT INTO "tblProfessions" ("ProfessionId", "Profession", "AltLanguage") VALUES (16, 'Police and military', 'Policier et militaire');"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblProfessions] ([ProfessionId], [Profession], [AltLanguage]) VALUES (17, 'Direct personal services staff', 'Personnel de services directs aux particuliers');"
            if settings.MSSQL else
            """INSERT INTO "tblProfessions" ("ProfessionId", "Profession", "AltLanguage") VALUES (17, 'Direct personal services staff', 'Personnel de services directs aux particuliers');"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblProfessions] ([ProfessionId], [Profession], [AltLanguage]) VALUES (18, 'Artist', 'Artiste');"
            if settings.MSSQL else
            """INSERT INTO "tblProfessions" ("ProfessionId", "Profession", "AltLanguage") VALUES (18, 'Artist', 'Artiste');"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblProfessions] ([ProfessionId], [Profession], [AltLanguage]) VALUES (19, 'Worker', 'Ouvrier');"
            if settings.MSSQL else
            """INSERT INTO "tblProfessions" ("ProfessionId", "Profession", "AltLanguage") VALUES (19, 'Worker', 'Ouvrier');"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblProfessions] ([ProfessionId], [Profession], [AltLanguage]) VALUES (20, 'Retired', 'Retraité');"
            if settings.MSSQL else
            """INSERT INTO "tblProfessions" ("ProfessionId", "Profession", "AltLanguage") VALUES (20, 'Retired', 'Retraité');"""
        ),
    ]
