# Generated by Django 4.2.11 on 2024-06-04 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0029_remove_familymutation_family'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymutation',
            old_name='family_uuid',
            new_name='family'
        ),
        migrations.AlterField(
            model_name='familymutation',
            name='family',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='insuree.family'),
        ),
    ]
