# Generated by Django 4.2.11 on 2025-11-30 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contribution_plan', '0013_alter_contributionplan_date_created_and_more'),
        ('insuree', '0031_couvertureassurancemutuelle_handicap_non_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilySizeScores',
            fields=[
                ('id', models.AutoField(db_column='FamilySizeScoresId', primary_key=True, serialize=False)),
                ('lower_born', models.IntegerField(db_column='LowerBorn')),
                ('higher_born', models.IntegerField(db_column='HigherBorn')),
                ('score', models.IntegerField(db_column='Score')),
            ],
            options={
                'db_table': 'tblFamilySizeScores',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='housingtype',
            name='score',
            field=models.IntegerField(blank=True, db_column='Score', null=True),
        ),
        migrations.AddField(
            model_name='incomelevels',
            name='score',
            field=models.IntegerField(blank=True, db_column='Score', null=True),
        ),
        migrations.CreateModel(
            name='ScoreContributionMapping',
            fields=[
                ('id', models.AutoField(db_column='ScoreContributionMappingId', primary_key=True, serialize=False)),
                ('lower_born', models.IntegerField(db_column='LowerBorn')),
                ('higher_born', models.IntegerField(db_column='HigherBorn')),
                ('contribution_plan', models.ForeignKey(blank=True, db_column='ContributionPlanID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contribution_plan.contributionplan')),
            ],
            options={
                'db_table': 'ScoreContributionMapping',
                'managed': True,
            },
        ),
    ]
