# Generated by Django 4.2.11 on 2025-12-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0035_family_size_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecontributionmapping',
            name='higher_born',
            field=models.DecimalField(db_column='HigherBorn', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='scorecontributionmapping',
            name='lower_born',
            field=models.DecimalField(db_column='LowerBorn', decimal_places=2, max_digits=10),
        ),
    ]
