# Generated by Django 4.2.11 on 2025-12-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0037_score_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyIncomeScores',
            fields=[
                ('id', models.AutoField(db_column='FamilyIncomeScoresId', primary_key=True, serialize=False)),
                ('lower_born', models.IntegerField(db_column='LowerBorn')),
                ('higher_born', models.IntegerField(db_column='HigherBorn')),
                ('score', models.IntegerField(db_column='Score')),
            ],
            options={
                'db_table': 'tblFamilyIncomeScores',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='insuree',
            name='fix_income',
            field=models.DecimalField(blank=True, db_column='FixIncome', decimal_places=2, max_digits=10, null=True),
        ),
    ]
